package com.tekpyramid.sp.enums;

public enum IssueType {
		TECHNICALSUPPORT, LICENSING, PRODUCTTRIALQUESTIONS, REPORTABUG, SUGGESTANEWFEATURE, SUGGESTIMPROVEMENT,
		EMAILEDREQUEST, OTHERQUESTIONS, BILLINGISSUE,PAYMENTISSUE,LOGINISSUE;
		
}
